# Site settings
title: 숲사람 모음집
# tag_text: soopsaram
description: the compilation of soopsaram

# Build settings
markdown: redcarpet
highlighter: pygments

redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data', 'footnotes']

# Enable when using kramdown
# kramdown:
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   use_coderay: false

exclude: ["README.md"]

google_tracking_id: UA-144742509-1
